// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1616484669;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__core__api_version_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "api_version",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::core::api_version())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__pairing__begin_pairing_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "begin_pairing",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_code = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::pairing::begin_pairing(api_code)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__pairing__cancel_pairing_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "cancel_pairing",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_device_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::pairing::cancel_pairing(api_device_id)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__pairing__confirm_pairing_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "confirm_pairing",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_device_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::pairing::confirm_pairing(api_device_id)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__events__core_event_stream_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "core_event_stream",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<
                crate::api::types::CoreEvent,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::events::core_event_stream(api_sink);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__core__core_init_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "core_init",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_support_dir = <String>::sse_decode(&mut deserializer);
            let api_radio = <crate::api::core::RadioChoice>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::core::core_init(api_support_dir, api_radio)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__core__core_version_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "core_version",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::core::core_version())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__identity__current_persona_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "current_persona",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::identity::current_persona()?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__core__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::core::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__messaging__list_threads_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_threads",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::messaging::list_threads()?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__discovery__nearby_devices_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "nearby_devices",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::discovery::nearby_devices()?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__transfers__offer_drop_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "offer_drop",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_device_id = <String>::sse_decode(&mut deserializer);
            let api_name = <String>::sse_decode(&mut deserializer);
            let api_size = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok =
                        crate::api::transfers::offer_drop(api_device_id, api_name, api_size)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__pairing__pairing_invite_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "pairing_invite",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::pairing::pairing_invite()?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__messaging__ping_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ping",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_device_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::messaging::ping(api_device_id)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__platform__platform_command_stream_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "platform_command_stream",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<
                crate::api::platform::HostCommand,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::platform::platform_command_stream(api_sink);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__platform__platform_fact_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "platform_fact",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_fact = <crate::api::platform::HostFact>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::platform::platform_fact(api_fact);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__messaging__send_chat_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "send_chat",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_device_id = <String>::sse_decode(&mut deserializer);
            let api_text = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::messaging::send_chat(api_device_id, api_text)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__discovery__set_discovery_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "set_discovery",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_enabled = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::discovery::set_discovery(api_enabled)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__pairing__stop_showing_invite_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "stop_showing_invite",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::pairing::stop_showing_invite()?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__messaging__thread_for_device_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "thread_for_device",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_device_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::messaging::thread_for_device(api_device_id)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__messaging__thread_messages_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "thread_messages",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_thread_id = <i64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::messaging::thread_messages(api_thread_id)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__identity__update_persona_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "update_persona",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_name = <String>::sse_decode(&mut deserializer);
            let api_colour = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::identity::update_persona(api_name, api_colour)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<crate::api::types::CoreEvent, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode
    for StreamSink<crate::api::platform::HostCommand, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::types::ChatMessageDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_msgId = <String>::sse_decode(deserializer);
        let mut var_threadId = <i64>::sse_decode(deserializer);
        let mut var_text = <String>::sse_decode(deserializer);
        let mut var_outgoing = <bool>::sse_decode(deserializer);
        let mut var_createdAt = <i64>::sse_decode(deserializer);
        return crate::api::types::ChatMessageDto {
            msg_id: var_msgId,
            thread_id: var_threadId,
            text: var_text,
            outgoing: var_outgoing,
            created_at: var_createdAt,
        };
    }
}

impl SseDecode for crate::api::types::CoreEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_devices =
                    <Vec<crate::api::types::NearbyDevice>>::sse_decode(deserializer);
                return crate::api::types::CoreEvent::DiscoveryUpdated {
                    devices: var_devices,
                };
            }
            1 => {
                let mut var_deviceId = <String>::sse_decode(deserializer);
                let mut var_name = <String>::sse_decode(deserializer);
                return crate::api::types::CoreEvent::Pinged {
                    device_id: var_deviceId,
                    name: var_name,
                };
            }
            2 => {
                let mut var_deviceId = <String>::sse_decode(deserializer);
                return crate::api::types::CoreEvent::PingAcked {
                    device_id: var_deviceId,
                };
            }
            3 => {
                let mut var_deviceId = <String>::sse_decode(deserializer);
                let mut var_reason = <String>::sse_decode(deserializer);
                return crate::api::types::CoreEvent::PingFailed {
                    device_id: var_deviceId,
                    reason: var_reason,
                };
            }
            4 => {
                let mut var_threadId = <i64>::sse_decode(deserializer);
                let mut var_msgId = <String>::sse_decode(deserializer);
                let mut var_text = <String>::sse_decode(deserializer);
                return crate::api::types::CoreEvent::MessageReceived {
                    thread_id: var_threadId,
                    msg_id: var_msgId,
                    text: var_text,
                };
            }
            5 => {
                let mut var_transferId = <String>::sse_decode(deserializer);
                let mut var_received = <u64>::sse_decode(deserializer);
                let mut var_total = <u64>::sse_decode(deserializer);
                return crate::api::types::CoreEvent::TransferProgress {
                    transfer_id: var_transferId,
                    received: var_received,
                    total: var_total,
                };
            }
            6 => {
                let mut var_transferId = <String>::sse_decode(deserializer);
                let mut var_success = <bool>::sse_decode(deserializer);
                return crate::api::types::CoreEvent::TransferCompleted {
                    transfer_id: var_transferId,
                    success: var_success,
                };
            }
            7 => {
                let mut var_deviceId = <String>::sse_decode(deserializer);
                let mut var_colours =
                    <Vec<crate::api::types::SasColourDto>>::sse_decode(deserializer);
                let mut var_word = <String>::sse_decode(deserializer);
                return crate::api::types::CoreEvent::PairingSas {
                    device_id: var_deviceId,
                    colours: var_colours,
                    word: var_word,
                };
            }
            8 => {
                let mut var_deviceId = <String>::sse_decode(deserializer);
                return crate::api::types::CoreEvent::PairingPeerConfirmed {
                    device_id: var_deviceId,
                };
            }
            9 => {
                let mut var_deviceId = <String>::sse_decode(deserializer);
                let mut var_threadId = <i64>::sse_decode(deserializer);
                let mut var_name = <String>::sse_decode(deserializer);
                let mut var_colour = <u32>::sse_decode(deserializer);
                return crate::api::types::CoreEvent::PairingCompleted {
                    device_id: var_deviceId,
                    thread_id: var_threadId,
                    name: var_name,
                    colour: var_colour,
                };
            }
            10 => {
                let mut var_deviceId = <String>::sse_decode(deserializer);
                let mut var_reason = <String>::sse_decode(deserializer);
                return crate::api::types::CoreEvent::PairingFailed {
                    device_id: var_deviceId,
                    reason: var_reason,
                };
            }
            11 => {
                let mut var_available = <bool>::sse_decode(deserializer);
                let mut var_reason = <Option<String>>::sse_decode(deserializer);
                return crate::api::types::CoreEvent::RadioChanged {
                    available: var_available,
                    reason: var_reason,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::platform::HostCommand {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_localId = <String>::sse_decode(deserializer);
                return crate::api::platform::HostCommand::BleSetLocalId {
                    local_id: var_localId,
                };
            }
            1 => {
                let mut var_payload = <Vec<u8>>::sse_decode(deserializer);
                return crate::api::platform::HostCommand::BleStartAdvertising {
                    payload: var_payload,
                };
            }
            2 => {
                return crate::api::platform::HostCommand::BleStopAdvertising;
            }
            3 => {
                return crate::api::platform::HostCommand::BleStartScanning;
            }
            4 => {
                return crate::api::platform::HostCommand::BleStopScanning;
            }
            5 => {
                let mut var_peer = <String>::sse_decode(deserializer);
                return crate::api::platform::HostCommand::BleConnect { peer: var_peer };
            }
            6 => {
                let mut var_peer = <String>::sse_decode(deserializer);
                let mut var_bytes = <Vec<u8>>::sse_decode(deserializer);
                return crate::api::platform::HostCommand::BleSend {
                    peer: var_peer,
                    bytes: var_bytes,
                };
            }
            7 => {
                let mut var_peer = <String>::sse_decode(deserializer);
                return crate::api::platform::HostCommand::BleDisconnect { peer: var_peer };
            }
            8 => {
                return crate::api::platform::HostCommand::BleShutdown;
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::platform::HostFact {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_peer = <String>::sse_decode(deserializer);
                let mut var_payload = <Vec<u8>>::sse_decode(deserializer);
                return crate::api::platform::HostFact::BlePeerFound {
                    peer: var_peer,
                    payload: var_payload,
                };
            }
            1 => {
                let mut var_peer = <String>::sse_decode(deserializer);
                return crate::api::platform::HostFact::BlePeerLost { peer: var_peer };
            }
            2 => {
                let mut var_peer = <String>::sse_decode(deserializer);
                return crate::api::platform::HostFact::BlePipeOpened { peer: var_peer };
            }
            3 => {
                let mut var_peer = <String>::sse_decode(deserializer);
                let mut var_why = <String>::sse_decode(deserializer);
                return crate::api::platform::HostFact::BlePipeFailed {
                    peer: var_peer,
                    why: var_why,
                };
            }
            4 => {
                let mut var_peer = <String>::sse_decode(deserializer);
                return crate::api::platform::HostFact::BlePipeClosed { peer: var_peer };
            }
            5 => {
                let mut var_peer = <String>::sse_decode(deserializer);
                let mut var_bytes = <Vec<u8>>::sse_decode(deserializer);
                return crate::api::platform::HostFact::BleReceived {
                    peer: var_peer,
                    bytes: var_bytes,
                };
            }
            6 => {
                let mut var_available = <bool>::sse_decode(deserializer);
                let mut var_reason = <Option<String>>::sse_decode(deserializer);
                return crate::api::platform::HostFact::BleAvailability {
                    available: var_available,
                    reason: var_reason,
                };
            }
            7 => {
                let mut var_peer = <String>::sse_decode(deserializer);
                let mut var_bytes = <u64>::sse_decode(deserializer);
                return crate::api::platform::HostFact::BleWriteComplete {
                    peer: var_peer,
                    bytes: var_bytes,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<crate::api::types::ChatMessageDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::types::ChatMessageDto>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::types::NearbyDevice> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::types::NearbyDevice>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::types::SasColourDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::types::SasColourDto>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::types::ThreadSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::types::ThreadSummary>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::types::NearbyDevice {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_deviceId = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_colour = <u32>::sse_decode(deserializer);
        let mut var_paired = <bool>::sse_decode(deserializer);
        return crate::api::types::NearbyDevice {
            device_id: var_deviceId,
            name: var_name,
            colour: var_colour,
            paired: var_paired,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<i64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::types::PersonaDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_colour = <u32>::sse_decode(deserializer);
        let mut var_version = <u32>::sse_decode(deserializer);
        let mut var_needsName = <bool>::sse_decode(deserializer);
        return crate::api::types::PersonaDto {
            name: var_name,
            colour: var_colour,
            version: var_version,
            needs_name: var_needsName,
        };
    }
}

impl SseDecode for crate::api::core::RadioChoice {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::core::RadioChoice::Lan,
            1 => crate::api::core::RadioChoice::Ble,
            _ => unreachable!("Invalid variant for RadioChoice: {}", inner),
        };
    }
}

impl SseDecode for crate::api::types::SasColourDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_rgb = <u32>::sse_decode(deserializer);
        return crate::api::types::SasColourDto {
            name: var_name,
            rgb: var_rgb,
        };
    }
}

impl SseDecode for crate::api::types::ThreadSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_threadId = <i64>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_colour = <u32>::sse_decode(deserializer);
        return crate::api::types::ThreadSummary {
            thread_id: var_threadId,
            name: var_name,
            colour: var_colour,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        2 => wire__crate__api__pairing__begin_pairing_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__pairing__cancel_pairing_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__pairing__confirm_pairing_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__events__core_event_stream_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__core__core_init_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__api__identity__current_persona_impl(port, ptr, rust_vec_len, data_len),
        9 => wire__crate__api__core__init_app_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__api__messaging__list_threads_impl(port, ptr, rust_vec_len, data_len),
        11 => wire__crate__api__discovery__nearby_devices_impl(port, ptr, rust_vec_len, data_len),
        12 => wire__crate__api__transfers__offer_drop_impl(port, ptr, rust_vec_len, data_len),
        13 => wire__crate__api__pairing__pairing_invite_impl(port, ptr, rust_vec_len, data_len),
        14 => wire__crate__api__messaging__ping_impl(port, ptr, rust_vec_len, data_len),
        15 => wire__crate__api__platform__platform_command_stream_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        16 => wire__crate__api__platform__platform_fact_impl(port, ptr, rust_vec_len, data_len),
        17 => wire__crate__api__messaging__send_chat_impl(port, ptr, rust_vec_len, data_len),
        18 => wire__crate__api__discovery__set_discovery_impl(port, ptr, rust_vec_len, data_len),
        19 => {
            wire__crate__api__pairing__stop_showing_invite_impl(port, ptr, rust_vec_len, data_len)
        }
        20 => {
            wire__crate__api__messaging__thread_for_device_impl(port, ptr, rust_vec_len, data_len)
        }
        21 => wire__crate__api__messaging__thread_messages_impl(port, ptr, rust_vec_len, data_len),
        22 => wire__crate__api__identity__update_persona_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__core__api_version_impl(ptr, rust_vec_len, data_len),
        7 => wire__crate__api__core__core_version_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::ChatMessageDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.msg_id.into_into_dart().into_dart(),
            self.thread_id.into_into_dart().into_dart(),
            self.text.into_into_dart().into_dart(),
            self.outgoing.into_into_dart().into_dart(),
            self.created_at.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::ChatMessageDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::ChatMessageDto>
    for crate::api::types::ChatMessageDto
{
    fn into_into_dart(self) -> crate::api::types::ChatMessageDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::CoreEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::types::CoreEvent::DiscoveryUpdated { devices } => {
                [0.into_dart(), devices.into_into_dart().into_dart()].into_dart()
            }
            crate::api::types::CoreEvent::Pinged { device_id, name } => [
                1.into_dart(),
                device_id.into_into_dart().into_dart(),
                name.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::types::CoreEvent::PingAcked { device_id } => {
                [2.into_dart(), device_id.into_into_dart().into_dart()].into_dart()
            }
            crate::api::types::CoreEvent::PingFailed { device_id, reason } => [
                3.into_dart(),
                device_id.into_into_dart().into_dart(),
                reason.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::types::CoreEvent::MessageReceived {
                thread_id,
                msg_id,
                text,
            } => [
                4.into_dart(),
                thread_id.into_into_dart().into_dart(),
                msg_id.into_into_dart().into_dart(),
                text.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::types::CoreEvent::TransferProgress {
                transfer_id,
                received,
                total,
            } => [
                5.into_dart(),
                transfer_id.into_into_dart().into_dart(),
                received.into_into_dart().into_dart(),
                total.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::types::CoreEvent::TransferCompleted {
                transfer_id,
                success,
            } => [
                6.into_dart(),
                transfer_id.into_into_dart().into_dart(),
                success.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::types::CoreEvent::PairingSas {
                device_id,
                colours,
                word,
            } => [
                7.into_dart(),
                device_id.into_into_dart().into_dart(),
                colours.into_into_dart().into_dart(),
                word.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::types::CoreEvent::PairingPeerConfirmed { device_id } => {
                [8.into_dart(), device_id.into_into_dart().into_dart()].into_dart()
            }
            crate::api::types::CoreEvent::PairingCompleted {
                device_id,
                thread_id,
                name,
                colour,
            } => [
                9.into_dart(),
                device_id.into_into_dart().into_dart(),
                thread_id.into_into_dart().into_dart(),
                name.into_into_dart().into_dart(),
                colour.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::types::CoreEvent::PairingFailed { device_id, reason } => [
                10.into_dart(),
                device_id.into_into_dart().into_dart(),
                reason.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::types::CoreEvent::RadioChanged { available, reason } => [
                11.into_dart(),
                available.into_into_dart().into_dart(),
                reason.into_into_dart().into_dart(),
            ]
            .into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::CoreEvent {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::CoreEvent>
    for crate::api::types::CoreEvent
{
    fn into_into_dart(self) -> crate::api::types::CoreEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::platform::HostCommand {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::platform::HostCommand::BleSetLocalId { local_id } => {
                [0.into_dart(), local_id.into_into_dart().into_dart()].into_dart()
            }
            crate::api::platform::HostCommand::BleStartAdvertising { payload } => {
                [1.into_dart(), payload.into_into_dart().into_dart()].into_dart()
            }
            crate::api::platform::HostCommand::BleStopAdvertising => [2.into_dart()].into_dart(),
            crate::api::platform::HostCommand::BleStartScanning => [3.into_dart()].into_dart(),
            crate::api::platform::HostCommand::BleStopScanning => [4.into_dart()].into_dart(),
            crate::api::platform::HostCommand::BleConnect { peer } => {
                [5.into_dart(), peer.into_into_dart().into_dart()].into_dart()
            }
            crate::api::platform::HostCommand::BleSend { peer, bytes } => [
                6.into_dart(),
                peer.into_into_dart().into_dart(),
                bytes.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::platform::HostCommand::BleDisconnect { peer } => {
                [7.into_dart(), peer.into_into_dart().into_dart()].into_dart()
            }
            crate::api::platform::HostCommand::BleShutdown => [8.into_dart()].into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::platform::HostCommand
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::platform::HostCommand>
    for crate::api::platform::HostCommand
{
    fn into_into_dart(self) -> crate::api::platform::HostCommand {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::platform::HostFact {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::platform::HostFact::BlePeerFound { peer, payload } => [
                0.into_dart(),
                peer.into_into_dart().into_dart(),
                payload.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::platform::HostFact::BlePeerLost { peer } => {
                [1.into_dart(), peer.into_into_dart().into_dart()].into_dart()
            }
            crate::api::platform::HostFact::BlePipeOpened { peer } => {
                [2.into_dart(), peer.into_into_dart().into_dart()].into_dart()
            }
            crate::api::platform::HostFact::BlePipeFailed { peer, why } => [
                3.into_dart(),
                peer.into_into_dart().into_dart(),
                why.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::platform::HostFact::BlePipeClosed { peer } => {
                [4.into_dart(), peer.into_into_dart().into_dart()].into_dart()
            }
            crate::api::platform::HostFact::BleReceived { peer, bytes } => [
                5.into_dart(),
                peer.into_into_dart().into_dart(),
                bytes.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::platform::HostFact::BleAvailability { available, reason } => [
                6.into_dart(),
                available.into_into_dart().into_dart(),
                reason.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::platform::HostFact::BleWriteComplete { peer, bytes } => [
                7.into_dart(),
                peer.into_into_dart().into_dart(),
                bytes.into_into_dart().into_dart(),
            ]
            .into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::platform::HostFact
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::platform::HostFact>
    for crate::api::platform::HostFact
{
    fn into_into_dart(self) -> crate::api::platform::HostFact {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::NearbyDevice {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.device_id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.colour.into_into_dart().into_dart(),
            self.paired.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::NearbyDevice
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::NearbyDevice>
    for crate::api::types::NearbyDevice
{
    fn into_into_dart(self) -> crate::api::types::NearbyDevice {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::PersonaDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.colour.into_into_dart().into_dart(),
            self.version.into_into_dart().into_dart(),
            self.needs_name.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::PersonaDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::PersonaDto>
    for crate::api::types::PersonaDto
{
    fn into_into_dart(self) -> crate::api::types::PersonaDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::core::RadioChoice {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Lan => 0.into_dart(),
            Self::Ble => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::core::RadioChoice {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::core::RadioChoice>
    for crate::api::core::RadioChoice
{
    fn into_into_dart(self) -> crate::api::core::RadioChoice {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::SasColourDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.rgb.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::SasColourDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::SasColourDto>
    for crate::api::types::SasColourDto
{
    fn into_into_dart(self) -> crate::api::types::SasColourDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::ThreadSummary {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.thread_id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.colour.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::ThreadSummary
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::ThreadSummary>
    for crate::api::types::ThreadSummary
{
    fn into_into_dart(self) -> crate::api::types::ThreadSummary {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<crate::api::types::CoreEvent, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode
    for StreamSink<crate::api::platform::HostCommand, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::types::ChatMessageDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.msg_id, serializer);
        <i64>::sse_encode(self.thread_id, serializer);
        <String>::sse_encode(self.text, serializer);
        <bool>::sse_encode(self.outgoing, serializer);
        <i64>::sse_encode(self.created_at, serializer);
    }
}

impl SseEncode for crate::api::types::CoreEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::types::CoreEvent::DiscoveryUpdated { devices } => {
                <i32>::sse_encode(0, serializer);
                <Vec<crate::api::types::NearbyDevice>>::sse_encode(devices, serializer);
            }
            crate::api::types::CoreEvent::Pinged { device_id, name } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(device_id, serializer);
                <String>::sse_encode(name, serializer);
            }
            crate::api::types::CoreEvent::PingAcked { device_id } => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(device_id, serializer);
            }
            crate::api::types::CoreEvent::PingFailed { device_id, reason } => {
                <i32>::sse_encode(3, serializer);
                <String>::sse_encode(device_id, serializer);
                <String>::sse_encode(reason, serializer);
            }
            crate::api::types::CoreEvent::MessageReceived {
                thread_id,
                msg_id,
                text,
            } => {
                <i32>::sse_encode(4, serializer);
                <i64>::sse_encode(thread_id, serializer);
                <String>::sse_encode(msg_id, serializer);
                <String>::sse_encode(text, serializer);
            }
            crate::api::types::CoreEvent::TransferProgress {
                transfer_id,
                received,
                total,
            } => {
                <i32>::sse_encode(5, serializer);
                <String>::sse_encode(transfer_id, serializer);
                <u64>::sse_encode(received, serializer);
                <u64>::sse_encode(total, serializer);
            }
            crate::api::types::CoreEvent::TransferCompleted {
                transfer_id,
                success,
            } => {
                <i32>::sse_encode(6, serializer);
                <String>::sse_encode(transfer_id, serializer);
                <bool>::sse_encode(success, serializer);
            }
            crate::api::types::CoreEvent::PairingSas {
                device_id,
                colours,
                word,
            } => {
                <i32>::sse_encode(7, serializer);
                <String>::sse_encode(device_id, serializer);
                <Vec<crate::api::types::SasColourDto>>::sse_encode(colours, serializer);
                <String>::sse_encode(word, serializer);
            }
            crate::api::types::CoreEvent::PairingPeerConfirmed { device_id } => {
                <i32>::sse_encode(8, serializer);
                <String>::sse_encode(device_id, serializer);
            }
            crate::api::types::CoreEvent::PairingCompleted {
                device_id,
                thread_id,
                name,
                colour,
            } => {
                <i32>::sse_encode(9, serializer);
                <String>::sse_encode(device_id, serializer);
                <i64>::sse_encode(thread_id, serializer);
                <String>::sse_encode(name, serializer);
                <u32>::sse_encode(colour, serializer);
            }
            crate::api::types::CoreEvent::PairingFailed { device_id, reason } => {
                <i32>::sse_encode(10, serializer);
                <String>::sse_encode(device_id, serializer);
                <String>::sse_encode(reason, serializer);
            }
            crate::api::types::CoreEvent::RadioChanged { available, reason } => {
                <i32>::sse_encode(11, serializer);
                <bool>::sse_encode(available, serializer);
                <Option<String>>::sse_encode(reason, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::platform::HostCommand {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::platform::HostCommand::BleSetLocalId { local_id } => {
                <i32>::sse_encode(0, serializer);
                <String>::sse_encode(local_id, serializer);
            }
            crate::api::platform::HostCommand::BleStartAdvertising { payload } => {
                <i32>::sse_encode(1, serializer);
                <Vec<u8>>::sse_encode(payload, serializer);
            }
            crate::api::platform::HostCommand::BleStopAdvertising => {
                <i32>::sse_encode(2, serializer);
            }
            crate::api::platform::HostCommand::BleStartScanning => {
                <i32>::sse_encode(3, serializer);
            }
            crate::api::platform::HostCommand::BleStopScanning => {
                <i32>::sse_encode(4, serializer);
            }
            crate::api::platform::HostCommand::BleConnect { peer } => {
                <i32>::sse_encode(5, serializer);
                <String>::sse_encode(peer, serializer);
            }
            crate::api::platform::HostCommand::BleSend { peer, bytes } => {
                <i32>::sse_encode(6, serializer);
                <String>::sse_encode(peer, serializer);
                <Vec<u8>>::sse_encode(bytes, serializer);
            }
            crate::api::platform::HostCommand::BleDisconnect { peer } => {
                <i32>::sse_encode(7, serializer);
                <String>::sse_encode(peer, serializer);
            }
            crate::api::platform::HostCommand::BleShutdown => {
                <i32>::sse_encode(8, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::platform::HostFact {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::platform::HostFact::BlePeerFound { peer, payload } => {
                <i32>::sse_encode(0, serializer);
                <String>::sse_encode(peer, serializer);
                <Vec<u8>>::sse_encode(payload, serializer);
            }
            crate::api::platform::HostFact::BlePeerLost { peer } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(peer, serializer);
            }
            crate::api::platform::HostFact::BlePipeOpened { peer } => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(peer, serializer);
            }
            crate::api::platform::HostFact::BlePipeFailed { peer, why } => {
                <i32>::sse_encode(3, serializer);
                <String>::sse_encode(peer, serializer);
                <String>::sse_encode(why, serializer);
            }
            crate::api::platform::HostFact::BlePipeClosed { peer } => {
                <i32>::sse_encode(4, serializer);
                <String>::sse_encode(peer, serializer);
            }
            crate::api::platform::HostFact::BleReceived { peer, bytes } => {
                <i32>::sse_encode(5, serializer);
                <String>::sse_encode(peer, serializer);
                <Vec<u8>>::sse_encode(bytes, serializer);
            }
            crate::api::platform::HostFact::BleAvailability { available, reason } => {
                <i32>::sse_encode(6, serializer);
                <bool>::sse_encode(available, serializer);
                <Option<String>>::sse_encode(reason, serializer);
            }
            crate::api::platform::HostFact::BleWriteComplete { peer, bytes } => {
                <i32>::sse_encode(7, serializer);
                <String>::sse_encode(peer, serializer);
                <u64>::sse_encode(bytes, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<crate::api::types::ChatMessageDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::types::ChatMessageDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::types::NearbyDevice> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::types::NearbyDevice>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::types::SasColourDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::types::SasColourDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::types::ThreadSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::types::ThreadSummary>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::types::NearbyDevice {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.device_id, serializer);
        <String>::sse_encode(self.name, serializer);
        <u32>::sse_encode(self.colour, serializer);
        <bool>::sse_encode(self.paired, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <i64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::types::PersonaDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <u32>::sse_encode(self.colour, serializer);
        <u32>::sse_encode(self.version, serializer);
        <bool>::sse_encode(self.needs_name, serializer);
    }
}

impl SseEncode for crate::api::core::RadioChoice {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::core::RadioChoice::Lan => 0,
                crate::api::core::RadioChoice::Ble => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::types::SasColourDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <u32>::sse_encode(self.rgb, serializer);
    }
}

impl SseEncode for crate::api::types::ThreadSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.thread_id, serializer);
        <String>::sse_encode(self.name, serializer);
        <u32>::sse_encode(self.colour, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
