// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/core.dart';
import 'api/discovery.dart';
import 'api/events.dart';
import 'api/identity.dart';
import 'api/messaging.dart';
import 'api/pairing.dart';
import 'api/platform.dart';
import 'api/transfers.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<CoreEvent> dco_decode_StreamSink_core_event_Sse(dynamic raw);

  @protected
  RustStreamSink<HostCommand> dco_decode_StreamSink_host_command_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  HostFact dco_decode_box_autoadd_host_fact(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  ChatMessageDto dco_decode_chat_message_dto(dynamic raw);

  @protected
  CoreEvent dco_decode_core_event(dynamic raw);

  @protected
  HostCommand dco_decode_host_command(dynamic raw);

  @protected
  HostFact dco_decode_host_fact(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<ChatMessageDto> dco_decode_list_chat_message_dto(dynamic raw);

  @protected
  List<NearbyDevice> dco_decode_list_nearby_device(dynamic raw);

  @protected
  List<PersonaColourDto> dco_decode_list_persona_colour_dto(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SasColourDto> dco_decode_list_sas_colour_dto(dynamic raw);

  @protected
  List<ThreadSummary> dco_decode_list_thread_summary(dynamic raw);

  @protected
  MessageStateDto dco_decode_message_state_dto(dynamic raw);

  @protected
  NearbyDevice dco_decode_nearby_device(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  PersonaColourDto dco_decode_persona_colour_dto(dynamic raw);

  @protected
  PersonaDto dco_decode_persona_dto(dynamic raw);

  @protected
  RadioChoice dco_decode_radio_choice(dynamic raw);

  @protected
  SasColourDto dco_decode_sas_colour_dto(dynamic raw);

  @protected
  ThreadSummary dco_decode_thread_summary(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<CoreEvent> sse_decode_StreamSink_core_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<HostCommand> sse_decode_StreamSink_host_command_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  HostFact sse_decode_box_autoadd_host_fact(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ChatMessageDto sse_decode_chat_message_dto(SseDeserializer deserializer);

  @protected
  CoreEvent sse_decode_core_event(SseDeserializer deserializer);

  @protected
  HostCommand sse_decode_host_command(SseDeserializer deserializer);

  @protected
  HostFact sse_decode_host_fact(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<ChatMessageDto> sse_decode_list_chat_message_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<NearbyDevice> sse_decode_list_nearby_device(
    SseDeserializer deserializer,
  );

  @protected
  List<PersonaColourDto> sse_decode_list_persona_colour_dto(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SasColourDto> sse_decode_list_sas_colour_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ThreadSummary> sse_decode_list_thread_summary(
    SseDeserializer deserializer,
  );

  @protected
  MessageStateDto sse_decode_message_state_dto(SseDeserializer deserializer);

  @protected
  NearbyDevice sse_decode_nearby_device(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  PersonaColourDto sse_decode_persona_colour_dto(SseDeserializer deserializer);

  @protected
  PersonaDto sse_decode_persona_dto(SseDeserializer deserializer);

  @protected
  RadioChoice sse_decode_radio_choice(SseDeserializer deserializer);

  @protected
  SasColourDto sse_decode_sas_colour_dto(SseDeserializer deserializer);

  @protected
  ThreadSummary sse_decode_thread_summary(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_core_event_Sse(
    RustStreamSink<CoreEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_host_command_Sse(
    RustStreamSink<HostCommand> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_host_fact(
    HostFact self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chat_message_dto(
    ChatMessageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_core_event(CoreEvent self, SseSerializer serializer);

  @protected
  void sse_encode_host_command(HostCommand self, SseSerializer serializer);

  @protected
  void sse_encode_host_fact(HostFact self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_chat_message_dto(
    List<ChatMessageDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_nearby_device(
    List<NearbyDevice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_persona_colour_dto(
    List<PersonaColourDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sas_colour_dto(
    List<SasColourDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_thread_summary(
    List<ThreadSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_message_state_dto(
    MessageStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_nearby_device(NearbyDevice self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_persona_colour_dto(
    PersonaColourDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_persona_dto(PersonaDto self, SseSerializer serializer);

  @protected
  void sse_encode_radio_choice(RadioChoice self, SseSerializer serializer);

  @protected
  void sse_encode_sas_colour_dto(SasColourDto self, SseSerializer serializer);

  @protected
  void sse_encode_thread_summary(ThreadSummary self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
