// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/core.dart';
import 'api/discovery.dart';
import 'api/events.dart';
import 'api/identity.dart';
import 'api/messaging.dart';
import 'api/pairing.dart';
import 'api/platform.dart';
import 'api/transfers.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiCoreInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1854925380;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_hoppler',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiCoreApiVersion();

  Future<String> crateApiPairingBeginPairing({required String code});

  Future<void> crateApiPairingCancelPairing({required String deviceId});

  Future<void> crateApiPairingConfirmPairing({required String deviceId});

  Stream<CoreEvent> crateApiEventsCoreEventStream();

  Future<PersonaDto> crateApiCoreCoreInit({
    required String supportDir,
    required RadioChoice radio,
  });

  String crateApiCoreCoreVersion();

  Future<PersonaDto> crateApiIdentityCurrentPersona();

  Future<void> crateApiCoreInitApp();

  Future<List<ThreadSummary>> crateApiMessagingListThreads();

  Future<List<NearbyDevice>> crateApiDiscoveryNearbyDevices();

  Future<String> crateApiTransfersOfferDrop({
    required String deviceId,
    required String name,
    required BigInt size,
  });

  Future<String> crateApiPairingPairingInvite();

  Future<List<PersonaColourDto>> crateApiIdentityPersonaColours();

  Future<void> crateApiMessagingPing({required String deviceId});

  Stream<HostCommand> crateApiPlatformPlatformCommandStream();

  Future<void> crateApiPlatformPlatformFact({required HostFact fact});

  Future<ChatMessageDto> crateApiMessagingSendChat({
    required String deviceId,
    required String text,
  });

  Future<ChatMessageDto> crateApiMessagingSendChatToThread({
    required PlatformInt64 threadId,
    required String text,
  });

  Future<void> crateApiDiscoverySetDiscovery({required bool enabled});

  Future<void> crateApiPairingStopShowingInvite();

  Future<PlatformInt64?> crateApiMessagingThreadForDevice({
    required String deviceId,
  });

  Future<List<ChatMessageDto>> crateApiMessagingThreadMessages({
    required PlatformInt64 threadId,
  });

  Future<PersonaDto> crateApiIdentityUpdatePersona({
    required String name,
    required int colour,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiCoreApiVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreApiVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreApiVersionConstMeta =>
      const TaskConstMeta(debugName: "api_version", argNames: []);

  @override
  Future<String> crateApiPairingBeginPairing({required String code}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(code, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPairingBeginPairingConstMeta,
        argValues: [code],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPairingBeginPairingConstMeta =>
      const TaskConstMeta(debugName: "begin_pairing", argNames: ["code"]);

  @override
  Future<void> crateApiPairingCancelPairing({required String deviceId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPairingCancelPairingConstMeta,
        argValues: [deviceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPairingCancelPairingConstMeta =>
      const TaskConstMeta(debugName: "cancel_pairing", argNames: ["deviceId"]);

  @override
  Future<void> crateApiPairingConfirmPairing({required String deviceId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPairingConfirmPairingConstMeta,
        argValues: [deviceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPairingConfirmPairingConstMeta =>
      const TaskConstMeta(debugName: "confirm_pairing", argNames: ["deviceId"]);

  @override
  Stream<CoreEvent> crateApiEventsCoreEventStream() {
    final sink = RustStreamSink<CoreEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_core_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 5,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiEventsCoreEventStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiEventsCoreEventStreamConstMeta =>
      const TaskConstMeta(debugName: "core_event_stream", argNames: ["sink"]);

  @override
  Future<PersonaDto> crateApiCoreCoreInit({
    required String supportDir,
    required RadioChoice radio,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(supportDir, serializer);
          sse_encode_radio_choice(radio, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_persona_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreCoreInitConstMeta,
        argValues: [supportDir, radio],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreCoreInitConstMeta => const TaskConstMeta(
    debugName: "core_init",
    argNames: ["supportDir", "radio"],
  );

  @override
  String crateApiCoreCoreVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreCoreVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreCoreVersionConstMeta =>
      const TaskConstMeta(debugName: "core_version", argNames: []);

  @override
  Future<PersonaDto> crateApiIdentityCurrentPersona() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_persona_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIdentityCurrentPersonaConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityCurrentPersonaConstMeta =>
      const TaskConstMeta(debugName: "current_persona", argNames: []);

  @override
  Future<void> crateApiCoreInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<ThreadSummary>> crateApiMessagingListThreads() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_thread_summary,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMessagingListThreadsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessagingListThreadsConstMeta =>
      const TaskConstMeta(debugName: "list_threads", argNames: []);

  @override
  Future<List<NearbyDevice>> crateApiDiscoveryNearbyDevices() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_nearby_device,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDiscoveryNearbyDevicesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDiscoveryNearbyDevicesConstMeta =>
      const TaskConstMeta(debugName: "nearby_devices", argNames: []);

  @override
  Future<String> crateApiTransfersOfferDrop({
    required String deviceId,
    required String name,
    required BigInt size,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(name, serializer);
          sse_encode_u_64(size, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTransfersOfferDropConstMeta,
        argValues: [deviceId, name, size],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransfersOfferDropConstMeta => const TaskConstMeta(
    debugName: "offer_drop",
    argNames: ["deviceId", "name", "size"],
  );

  @override
  Future<String> crateApiPairingPairingInvite() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPairingPairingInviteConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPairingPairingInviteConstMeta =>
      const TaskConstMeta(debugName: "pairing_invite", argNames: []);

  @override
  Future<List<PersonaColourDto>> crateApiIdentityPersonaColours() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_persona_colour_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIdentityPersonaColoursConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityPersonaColoursConstMeta =>
      const TaskConstMeta(debugName: "persona_colours", argNames: []);

  @override
  Future<void> crateApiMessagingPing({required String deviceId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMessagingPingConstMeta,
        argValues: [deviceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessagingPingConstMeta =>
      const TaskConstMeta(debugName: "ping", argNames: ["deviceId"]);

  @override
  Stream<HostCommand> crateApiPlatformPlatformCommandStream() {
    final sink = RustStreamSink<HostCommand>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_host_command_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 16,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiPlatformPlatformCommandStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiPlatformPlatformCommandStreamConstMeta =>
      const TaskConstMeta(
        debugName: "platform_command_stream",
        argNames: ["sink"],
      );

  @override
  Future<void> crateApiPlatformPlatformFact({required HostFact fact}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_host_fact(fact, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlatformPlatformFactConstMeta,
        argValues: [fact],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlatformPlatformFactConstMeta =>
      const TaskConstMeta(debugName: "platform_fact", argNames: ["fact"]);

  @override
  Future<ChatMessageDto> crateApiMessagingSendChat({
    required String deviceId,
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_chat_message_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMessagingSendChatConstMeta,
        argValues: [deviceId, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessagingSendChatConstMeta => const TaskConstMeta(
    debugName: "send_chat",
    argNames: ["deviceId", "text"],
  );

  @override
  Future<ChatMessageDto> crateApiMessagingSendChatToThread({
    required PlatformInt64 threadId,
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(threadId, serializer);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_chat_message_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMessagingSendChatToThreadConstMeta,
        argValues: [threadId, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessagingSendChatToThreadConstMeta =>
      const TaskConstMeta(
        debugName: "send_chat_to_thread",
        argNames: ["threadId", "text"],
      );

  @override
  Future<void> crateApiDiscoverySetDiscovery({required bool enabled}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDiscoverySetDiscoveryConstMeta,
        argValues: [enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDiscoverySetDiscoveryConstMeta =>
      const TaskConstMeta(debugName: "set_discovery", argNames: ["enabled"]);

  @override
  Future<void> crateApiPairingStopShowingInvite() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPairingStopShowingInviteConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPairingStopShowingInviteConstMeta =>
      const TaskConstMeta(debugName: "stop_showing_invite", argNames: []);

  @override
  Future<PlatformInt64?> crateApiMessagingThreadForDevice({
    required String deviceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMessagingThreadForDeviceConstMeta,
        argValues: [deviceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessagingThreadForDeviceConstMeta =>
      const TaskConstMeta(
        debugName: "thread_for_device",
        argNames: ["deviceId"],
      );

  @override
  Future<List<ChatMessageDto>> crateApiMessagingThreadMessages({
    required PlatformInt64 threadId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(threadId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_chat_message_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMessagingThreadMessagesConstMeta,
        argValues: [threadId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessagingThreadMessagesConstMeta =>
      const TaskConstMeta(debugName: "thread_messages", argNames: ["threadId"]);

  @override
  Future<PersonaDto> crateApiIdentityUpdatePersona({
    required String name,
    required int colour,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_u_32(colour, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_persona_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIdentityUpdatePersonaConstMeta,
        argValues: [name, colour],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityUpdatePersonaConstMeta =>
      const TaskConstMeta(
        debugName: "update_persona",
        argNames: ["name", "colour"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<CoreEvent> dco_decode_StreamSink_core_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<HostCommand> dco_decode_StreamSink_host_command_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  HostFact dco_decode_box_autoadd_host_fact(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_host_fact(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  ChatMessageDto dco_decode_chat_message_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ChatMessageDto(
      msgId: dco_decode_String(arr[0]),
      threadId: dco_decode_i_64(arr[1]),
      text: dco_decode_String(arr[2]),
      outgoing: dco_decode_bool(arr[3]),
      createdAt: dco_decode_i_64(arr[4]),
      state: dco_decode_message_state_dto(arr[5]),
    );
  }

  @protected
  CoreEvent dco_decode_core_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return CoreEvent_DiscoveryUpdated(
          devices: dco_decode_list_nearby_device(raw[1]),
        );
      case 1:
        return CoreEvent_Pinged(
          deviceId: dco_decode_String(raw[1]),
          name: dco_decode_String(raw[2]),
        );
      case 2:
        return CoreEvent_PingAcked(deviceId: dco_decode_String(raw[1]));
      case 3:
        return CoreEvent_PingFailed(
          deviceId: dco_decode_String(raw[1]),
          reason: dco_decode_String(raw[2]),
        );
      case 4:
        return CoreEvent_MessageReceived(
          threadId: dco_decode_i_64(raw[1]),
          msgId: dco_decode_String(raw[2]),
          text: dco_decode_String(raw[3]),
        );
      case 5:
        return CoreEvent_TransferProgress(
          transferId: dco_decode_String(raw[1]),
          received: dco_decode_u_64(raw[2]),
          total: dco_decode_u_64(raw[3]),
        );
      case 6:
        return CoreEvent_TransferCompleted(
          transferId: dco_decode_String(raw[1]),
          success: dco_decode_bool(raw[2]),
        );
      case 7:
        return CoreEvent_PairingSas(
          deviceId: dco_decode_String(raw[1]),
          colours: dco_decode_list_sas_colour_dto(raw[2]),
          word: dco_decode_String(raw[3]),
        );
      case 8:
        return CoreEvent_PairingPeerConfirmed(
          deviceId: dco_decode_String(raw[1]),
        );
      case 9:
        return CoreEvent_PairingCompleted(
          deviceId: dco_decode_String(raw[1]),
          threadId: dco_decode_i_64(raw[2]),
          name: dco_decode_String(raw[3]),
          colour: dco_decode_u_32(raw[4]),
        );
      case 10:
        return CoreEvent_PairingFailed(
          deviceId: dco_decode_String(raw[1]),
          reason: dco_decode_String(raw[2]),
        );
      case 11:
        return CoreEvent_RadioChanged(
          available: dco_decode_bool(raw[1]),
          reason: dco_decode_opt_String(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  HostCommand dco_decode_host_command(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return HostCommand_BleSetLocalId(localId: dco_decode_String(raw[1]));
      case 1:
        return HostCommand_BleStartAdvertising(
          payload: dco_decode_list_prim_u_8_strict(raw[1]),
        );
      case 2:
        return HostCommand_BleStopAdvertising();
      case 3:
        return HostCommand_BleStartScanning();
      case 4:
        return HostCommand_BleStopScanning();
      case 5:
        return HostCommand_BleConnect(peer: dco_decode_String(raw[1]));
      case 6:
        return HostCommand_BleSend(
          peer: dco_decode_String(raw[1]),
          bytes: dco_decode_list_prim_u_8_strict(raw[2]),
        );
      case 7:
        return HostCommand_BleDisconnect(peer: dco_decode_String(raw[1]));
      case 8:
        return HostCommand_BleShutdown();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  HostFact dco_decode_host_fact(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return HostFact_BlePeerFound(
          peer: dco_decode_String(raw[1]),
          payload: dco_decode_list_prim_u_8_strict(raw[2]),
        );
      case 1:
        return HostFact_BlePeerLost(peer: dco_decode_String(raw[1]));
      case 2:
        return HostFact_BlePipeOpened(peer: dco_decode_String(raw[1]));
      case 3:
        return HostFact_BlePipeFailed(
          peer: dco_decode_String(raw[1]),
          why: dco_decode_String(raw[2]),
        );
      case 4:
        return HostFact_BlePipeClosed(peer: dco_decode_String(raw[1]));
      case 5:
        return HostFact_BleReceived(
          peer: dco_decode_String(raw[1]),
          bytes: dco_decode_list_prim_u_8_strict(raw[2]),
        );
      case 6:
        return HostFact_BleAvailability(
          available: dco_decode_bool(raw[1]),
          reason: dco_decode_opt_String(raw[2]),
        );
      case 7:
        return HostFact_BleWriteComplete(
          peer: dco_decode_String(raw[1]),
          bytes: dco_decode_u_64(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<ChatMessageDto> dco_decode_list_chat_message_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chat_message_dto).toList();
  }

  @protected
  List<NearbyDevice> dco_decode_list_nearby_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_nearby_device).toList();
  }

  @protected
  List<PersonaColourDto> dco_decode_list_persona_colour_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_persona_colour_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SasColourDto> dco_decode_list_sas_colour_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_sas_colour_dto).toList();
  }

  @protected
  List<ThreadSummary> dco_decode_list_thread_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_thread_summary).toList();
  }

  @protected
  MessageStateDto dco_decode_message_state_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MessageStateDto.values[raw as int];
  }

  @protected
  NearbyDevice dco_decode_nearby_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return NearbyDevice(
      deviceId: dco_decode_opt_String(arr[0]),
      threadId: dco_decode_opt_box_autoadd_i_64(arr[1]),
      name: dco_decode_String(arr[2]),
      colour: dco_decode_u_32(arr[3]),
      paired: dco_decode_bool(arr[4]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  PersonaColourDto dco_decode_persona_colour_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PersonaColourDto(
      name: dco_decode_String(arr[0]),
      value: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  PersonaDto dco_decode_persona_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PersonaDto(
      name: dco_decode_String(arr[0]),
      colour: dco_decode_u_32(arr[1]),
      version: dco_decode_u_32(arr[2]),
      needsName: dco_decode_bool(arr[3]),
    );
  }

  @protected
  RadioChoice dco_decode_radio_choice(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RadioChoice.values[raw as int];
  }

  @protected
  SasColourDto dco_decode_sas_colour_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SasColourDto(
      name: dco_decode_String(arr[0]),
      rgb: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  ThreadSummary dco_decode_thread_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ThreadSummary(
      threadId: dco_decode_i_64(arr[0]),
      name: dco_decode_String(arr[1]),
      colour: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<CoreEvent> sse_decode_StreamSink_core_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<HostCommand> sse_decode_StreamSink_host_command_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  HostFact sse_decode_box_autoadd_host_fact(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_host_fact(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  ChatMessageDto sse_decode_chat_message_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_msgId = sse_decode_String(deserializer);
    var var_threadId = sse_decode_i_64(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_outgoing = sse_decode_bool(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_state = sse_decode_message_state_dto(deserializer);
    return ChatMessageDto(
      msgId: var_msgId,
      threadId: var_threadId,
      text: var_text,
      outgoing: var_outgoing,
      createdAt: var_createdAt,
      state: var_state,
    );
  }

  @protected
  CoreEvent sse_decode_core_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_devices = sse_decode_list_nearby_device(deserializer);
        return CoreEvent_DiscoveryUpdated(devices: var_devices);
      case 1:
        var var_deviceId = sse_decode_String(deserializer);
        var var_name = sse_decode_String(deserializer);
        return CoreEvent_Pinged(deviceId: var_deviceId, name: var_name);
      case 2:
        var var_deviceId = sse_decode_String(deserializer);
        return CoreEvent_PingAcked(deviceId: var_deviceId);
      case 3:
        var var_deviceId = sse_decode_String(deserializer);
        var var_reason = sse_decode_String(deserializer);
        return CoreEvent_PingFailed(deviceId: var_deviceId, reason: var_reason);
      case 4:
        var var_threadId = sse_decode_i_64(deserializer);
        var var_msgId = sse_decode_String(deserializer);
        var var_text = sse_decode_String(deserializer);
        return CoreEvent_MessageReceived(
          threadId: var_threadId,
          msgId: var_msgId,
          text: var_text,
        );
      case 5:
        var var_transferId = sse_decode_String(deserializer);
        var var_received = sse_decode_u_64(deserializer);
        var var_total = sse_decode_u_64(deserializer);
        return CoreEvent_TransferProgress(
          transferId: var_transferId,
          received: var_received,
          total: var_total,
        );
      case 6:
        var var_transferId = sse_decode_String(deserializer);
        var var_success = sse_decode_bool(deserializer);
        return CoreEvent_TransferCompleted(
          transferId: var_transferId,
          success: var_success,
        );
      case 7:
        var var_deviceId = sse_decode_String(deserializer);
        var var_colours = sse_decode_list_sas_colour_dto(deserializer);
        var var_word = sse_decode_String(deserializer);
        return CoreEvent_PairingSas(
          deviceId: var_deviceId,
          colours: var_colours,
          word: var_word,
        );
      case 8:
        var var_deviceId = sse_decode_String(deserializer);
        return CoreEvent_PairingPeerConfirmed(deviceId: var_deviceId);
      case 9:
        var var_deviceId = sse_decode_String(deserializer);
        var var_threadId = sse_decode_i_64(deserializer);
        var var_name = sse_decode_String(deserializer);
        var var_colour = sse_decode_u_32(deserializer);
        return CoreEvent_PairingCompleted(
          deviceId: var_deviceId,
          threadId: var_threadId,
          name: var_name,
          colour: var_colour,
        );
      case 10:
        var var_deviceId = sse_decode_String(deserializer);
        var var_reason = sse_decode_String(deserializer);
        return CoreEvent_PairingFailed(
          deviceId: var_deviceId,
          reason: var_reason,
        );
      case 11:
        var var_available = sse_decode_bool(deserializer);
        var var_reason = sse_decode_opt_String(deserializer);
        return CoreEvent_RadioChanged(
          available: var_available,
          reason: var_reason,
        );
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  HostCommand sse_decode_host_command(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_localId = sse_decode_String(deserializer);
        return HostCommand_BleSetLocalId(localId: var_localId);
      case 1:
        var var_payload = sse_decode_list_prim_u_8_strict(deserializer);
        return HostCommand_BleStartAdvertising(payload: var_payload);
      case 2:
        return HostCommand_BleStopAdvertising();
      case 3:
        return HostCommand_BleStartScanning();
      case 4:
        return HostCommand_BleStopScanning();
      case 5:
        var var_peer = sse_decode_String(deserializer);
        return HostCommand_BleConnect(peer: var_peer);
      case 6:
        var var_peer = sse_decode_String(deserializer);
        var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
        return HostCommand_BleSend(peer: var_peer, bytes: var_bytes);
      case 7:
        var var_peer = sse_decode_String(deserializer);
        return HostCommand_BleDisconnect(peer: var_peer);
      case 8:
        return HostCommand_BleShutdown();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  HostFact sse_decode_host_fact(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_peer = sse_decode_String(deserializer);
        var var_payload = sse_decode_list_prim_u_8_strict(deserializer);
        return HostFact_BlePeerFound(peer: var_peer, payload: var_payload);
      case 1:
        var var_peer = sse_decode_String(deserializer);
        return HostFact_BlePeerLost(peer: var_peer);
      case 2:
        var var_peer = sse_decode_String(deserializer);
        return HostFact_BlePipeOpened(peer: var_peer);
      case 3:
        var var_peer = sse_decode_String(deserializer);
        var var_why = sse_decode_String(deserializer);
        return HostFact_BlePipeFailed(peer: var_peer, why: var_why);
      case 4:
        var var_peer = sse_decode_String(deserializer);
        return HostFact_BlePipeClosed(peer: var_peer);
      case 5:
        var var_peer = sse_decode_String(deserializer);
        var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
        return HostFact_BleReceived(peer: var_peer, bytes: var_bytes);
      case 6:
        var var_available = sse_decode_bool(deserializer);
        var var_reason = sse_decode_opt_String(deserializer);
        return HostFact_BleAvailability(
          available: var_available,
          reason: var_reason,
        );
      case 7:
        var var_peer = sse_decode_String(deserializer);
        var var_bytes = sse_decode_u_64(deserializer);
        return HostFact_BleWriteComplete(peer: var_peer, bytes: var_bytes);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<ChatMessageDto> sse_decode_list_chat_message_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChatMessageDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chat_message_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<NearbyDevice> sse_decode_list_nearby_device(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NearbyDevice>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_nearby_device(deserializer));
    }
    return ans_;
  }

  @protected
  List<PersonaColourDto> sse_decode_list_persona_colour_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PersonaColourDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_persona_colour_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SasColourDto> sse_decode_list_sas_colour_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SasColourDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_sas_colour_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<ThreadSummary> sse_decode_list_thread_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ThreadSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_thread_summary(deserializer));
    }
    return ans_;
  }

  @protected
  MessageStateDto sse_decode_message_state_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MessageStateDto.values[inner];
  }

  @protected
  NearbyDevice sse_decode_nearby_device(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceId = sse_decode_opt_String(deserializer);
    var var_threadId = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_colour = sse_decode_u_32(deserializer);
    var var_paired = sse_decode_bool(deserializer);
    return NearbyDevice(
      deviceId: var_deviceId,
      threadId: var_threadId,
      name: var_name,
      colour: var_colour,
      paired: var_paired,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PersonaColourDto sse_decode_persona_colour_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_value = sse_decode_u_32(deserializer);
    return PersonaColourDto(name: var_name, value: var_value);
  }

  @protected
  PersonaDto sse_decode_persona_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_colour = sse_decode_u_32(deserializer);
    var var_version = sse_decode_u_32(deserializer);
    var var_needsName = sse_decode_bool(deserializer);
    return PersonaDto(
      name: var_name,
      colour: var_colour,
      version: var_version,
      needsName: var_needsName,
    );
  }

  @protected
  RadioChoice sse_decode_radio_choice(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return RadioChoice.values[inner];
  }

  @protected
  SasColourDto sse_decode_sas_colour_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_rgb = sse_decode_u_32(deserializer);
    return SasColourDto(name: var_name, rgb: var_rgb);
  }

  @protected
  ThreadSummary sse_decode_thread_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_threadId = sse_decode_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_colour = sse_decode_u_32(deserializer);
    return ThreadSummary(
      threadId: var_threadId,
      name: var_name,
      colour: var_colour,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_core_event_Sse(
    RustStreamSink<CoreEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_core_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_host_command_Sse(
    RustStreamSink<HostCommand> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_host_command,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_host_fact(
    HostFact self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_host_fact(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_chat_message_dto(
    ChatMessageDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.msgId, serializer);
    sse_encode_i_64(self.threadId, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_bool(self.outgoing, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_message_state_dto(self.state, serializer);
  }

  @protected
  void sse_encode_core_event(CoreEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case CoreEvent_DiscoveryUpdated(devices: final devices):
        sse_encode_i_32(0, serializer);
        sse_encode_list_nearby_device(devices, serializer);
      case CoreEvent_Pinged(deviceId: final deviceId, name: final name):
        sse_encode_i_32(1, serializer);
        sse_encode_String(deviceId, serializer);
        sse_encode_String(name, serializer);
      case CoreEvent_PingAcked(deviceId: final deviceId):
        sse_encode_i_32(2, serializer);
        sse_encode_String(deviceId, serializer);
      case CoreEvent_PingFailed(deviceId: final deviceId, reason: final reason):
        sse_encode_i_32(3, serializer);
        sse_encode_String(deviceId, serializer);
        sse_encode_String(reason, serializer);
      case CoreEvent_MessageReceived(
        threadId: final threadId,
        msgId: final msgId,
        text: final text,
      ):
        sse_encode_i_32(4, serializer);
        sse_encode_i_64(threadId, serializer);
        sse_encode_String(msgId, serializer);
        sse_encode_String(text, serializer);
      case CoreEvent_TransferProgress(
        transferId: final transferId,
        received: final received,
        total: final total,
      ):
        sse_encode_i_32(5, serializer);
        sse_encode_String(transferId, serializer);
        sse_encode_u_64(received, serializer);
        sse_encode_u_64(total, serializer);
      case CoreEvent_TransferCompleted(
        transferId: final transferId,
        success: final success,
      ):
        sse_encode_i_32(6, serializer);
        sse_encode_String(transferId, serializer);
        sse_encode_bool(success, serializer);
      case CoreEvent_PairingSas(
        deviceId: final deviceId,
        colours: final colours,
        word: final word,
      ):
        sse_encode_i_32(7, serializer);
        sse_encode_String(deviceId, serializer);
        sse_encode_list_sas_colour_dto(colours, serializer);
        sse_encode_String(word, serializer);
      case CoreEvent_PairingPeerConfirmed(deviceId: final deviceId):
        sse_encode_i_32(8, serializer);
        sse_encode_String(deviceId, serializer);
      case CoreEvent_PairingCompleted(
        deviceId: final deviceId,
        threadId: final threadId,
        name: final name,
        colour: final colour,
      ):
        sse_encode_i_32(9, serializer);
        sse_encode_String(deviceId, serializer);
        sse_encode_i_64(threadId, serializer);
        sse_encode_String(name, serializer);
        sse_encode_u_32(colour, serializer);
      case CoreEvent_PairingFailed(
        deviceId: final deviceId,
        reason: final reason,
      ):
        sse_encode_i_32(10, serializer);
        sse_encode_String(deviceId, serializer);
        sse_encode_String(reason, serializer);
      case CoreEvent_RadioChanged(
        available: final available,
        reason: final reason,
      ):
        sse_encode_i_32(11, serializer);
        sse_encode_bool(available, serializer);
        sse_encode_opt_String(reason, serializer);
    }
  }

  @protected
  void sse_encode_host_command(HostCommand self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case HostCommand_BleSetLocalId(localId: final localId):
        sse_encode_i_32(0, serializer);
        sse_encode_String(localId, serializer);
      case HostCommand_BleStartAdvertising(payload: final payload):
        sse_encode_i_32(1, serializer);
        sse_encode_list_prim_u_8_strict(payload, serializer);
      case HostCommand_BleStopAdvertising():
        sse_encode_i_32(2, serializer);
      case HostCommand_BleStartScanning():
        sse_encode_i_32(3, serializer);
      case HostCommand_BleStopScanning():
        sse_encode_i_32(4, serializer);
      case HostCommand_BleConnect(peer: final peer):
        sse_encode_i_32(5, serializer);
        sse_encode_String(peer, serializer);
      case HostCommand_BleSend(peer: final peer, bytes: final bytes):
        sse_encode_i_32(6, serializer);
        sse_encode_String(peer, serializer);
        sse_encode_list_prim_u_8_strict(bytes, serializer);
      case HostCommand_BleDisconnect(peer: final peer):
        sse_encode_i_32(7, serializer);
        sse_encode_String(peer, serializer);
      case HostCommand_BleShutdown():
        sse_encode_i_32(8, serializer);
    }
  }

  @protected
  void sse_encode_host_fact(HostFact self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case HostFact_BlePeerFound(peer: final peer, payload: final payload):
        sse_encode_i_32(0, serializer);
        sse_encode_String(peer, serializer);
        sse_encode_list_prim_u_8_strict(payload, serializer);
      case HostFact_BlePeerLost(peer: final peer):
        sse_encode_i_32(1, serializer);
        sse_encode_String(peer, serializer);
      case HostFact_BlePipeOpened(peer: final peer):
        sse_encode_i_32(2, serializer);
        sse_encode_String(peer, serializer);
      case HostFact_BlePipeFailed(peer: final peer, why: final why):
        sse_encode_i_32(3, serializer);
        sse_encode_String(peer, serializer);
        sse_encode_String(why, serializer);
      case HostFact_BlePipeClosed(peer: final peer):
        sse_encode_i_32(4, serializer);
        sse_encode_String(peer, serializer);
      case HostFact_BleReceived(peer: final peer, bytes: final bytes):
        sse_encode_i_32(5, serializer);
        sse_encode_String(peer, serializer);
        sse_encode_list_prim_u_8_strict(bytes, serializer);
      case HostFact_BleAvailability(
        available: final available,
        reason: final reason,
      ):
        sse_encode_i_32(6, serializer);
        sse_encode_bool(available, serializer);
        sse_encode_opt_String(reason, serializer);
      case HostFact_BleWriteComplete(peer: final peer, bytes: final bytes):
        sse_encode_i_32(7, serializer);
        sse_encode_String(peer, serializer);
        sse_encode_u_64(bytes, serializer);
    }
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_chat_message_dto(
    List<ChatMessageDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chat_message_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_nearby_device(
    List<NearbyDevice> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_nearby_device(item, serializer);
    }
  }

  @protected
  void sse_encode_list_persona_colour_dto(
    List<PersonaColourDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_persona_colour_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_sas_colour_dto(
    List<SasColourDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_sas_colour_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_thread_summary(
    List<ThreadSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_thread_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_message_state_dto(
    MessageStateDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_nearby_device(NearbyDevice self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.deviceId, serializer);
    sse_encode_opt_box_autoadd_i_64(self.threadId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_u_32(self.colour, serializer);
    sse_encode_bool(self.paired, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_persona_colour_dto(
    PersonaColourDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_u_32(self.value, serializer);
  }

  @protected
  void sse_encode_persona_dto(PersonaDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_u_32(self.colour, serializer);
    sse_encode_u_32(self.version, serializer);
    sse_encode_bool(self.needsName, serializer);
  }

  @protected
  void sse_encode_radio_choice(RadioChoice self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_sas_colour_dto(SasColourDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_u_32(self.rgb, serializer);
  }

  @protected
  void sse_encode_thread_summary(ThreadSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.threadId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_u_32(self.colour, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
