// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

String coreVersion() => RustLib.instance.api.crateApiCoreCoreVersion();

/// The core API contract version. Breaking changes to any `crate::api` surface
/// bump this (and `docs/CORE_API.md`).
String apiVersion() => RustLib.instance.api.crateApiCoreApiVersion();

/// Initialise the core at `support_dir` (the app's private data directory).
/// Returns the local persona. Call once at startup, before other API calls.
Future<PersonaDto> coreInit({
  required String supportDir,
  required RadioChoice radio,
}) => RustLib.instance.api.crateApiCoreCoreInit(
  supportDir: supportDir,
  radio: radio,
);

/// Destroy everything this device is (R0-F9).
///
/// Irreversible. Afterwards there is no identity, no conversation and no file
/// left, and the core is not running: call `core_init` again to come back, and
/// it will be a first launch — a new identity, and nobody recognises this
/// device as who it was.
///
/// The guarded gesture that reaches this is the caller's; there is no second
/// confirmation in here.
Future<void> wipe({required String supportDir}) =>
    RustLib.instance.api.crateApiCoreWipe(supportDir: supportDir);

/// Which radio the core should run on.
///
/// One rung, not the tech spec §9 ladder — running several at once is T15's
/// job. The choice exists because the BLE acceptance needs the radio in
/// isolation: with LAN also running, a peer found over Wi-Fi looks exactly like
/// one found over the air and the run proves nothing about the radio.
enum RadioChoice {
  /// mDNS and TCP. The default, and what every hardware run so far used.
  lan,

  /// The BLE rung, driven through the host seam. A host dispatcher must be
  /// attached before `core_init` or every command simply queues.
  ble,
}
