// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Turn Discovery on or off. Emits `discovery.updated`.
Future<void> setDiscovery({required bool enabled}) =>
    RustLib.instance.api.crateApiDiscoverySetDiscovery(enabled: enabled);

/// The devices currently visible (empty when Discovery is off).
Future<List<NearbyDevice>> nearbyDevices() =>
    RustLib.instance.api.crateApiDiscoveryNearbyDevices();
