// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Turn Discovery on or off. Emits `discovery.updated`.
Future<void> setDiscovery({required bool enabled}) =>
    RustLib.instance.api.crateApiDiscoverySetDiscovery(enabled: enabled);

/// The devices currently visible (empty when Discovery is off).
Future<List<NearbyDevice>> nearbyDevices() =>
    RustLib.instance.api.crateApiDiscoveryNearbyDevices();

/// Block a device (R0-F10). Silent and local: nothing reaches the person
/// blocked, and being blocked is indistinguishable from this device having
/// Discovery closed.
///
/// Revokes any pairing with them, tears down any live session, and takes them
/// off the nearby list. Emits `discovery.updated`.
Future<void> blockDevice({required String deviceId}) =>
    RustLib.instance.api.crateApiDiscoveryBlockDevice(deviceId: deviceId);
