// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Turn Discovery on or off. Emits `discovery.updated`.
Future<void> setDiscovery({required bool enabled}) =>
    RustLib.instance.api.crateApiDiscoverySetDiscovery(enabled: enabled);

/// The devices currently visible (empty when Discovery is off).
Future<List<NearbyDevice>> nearbyDevices() =>
    RustLib.instance.api.crateApiDiscoveryNearbyDevices();

/// Block a device (R0-F10). Silent and local: nothing reaches the person
/// blocked, and being blocked is indistinguishable from this device having
/// Discovery closed.
///
/// Revokes any pairing with them, tears down any live session, and takes them
/// off the nearby list. Emits `discovery.updated`.
Future<void> blockDevice({required String deviceId}) =>
    RustLib.instance.api.crateApiDiscoveryBlockDevice(deviceId: deviceId);

/// Block the person a conversation is with (R0-F10).
///
/// The way to block somebody who is out of range: a paired friend has a thread
/// whether the radio can see them or not, and no `device_id` while they are
/// away.
Future<void> blockThread({required PlatformInt64 threadId}) =>
    RustLib.instance.api.crateApiDiscoveryBlockThread(threadId: threadId);

/// Lift a block. Restores stranger-level status and **not** the pairing it
/// revoked (R0-F10).
Future<void> unblockPerson({required PlatformInt64 contactId}) =>
    RustLib.instance.api.crateApiDiscoveryUnblockPerson(contactId: contactId);

/// Everyone this device is currently refusing.
Future<List<BlockedPersonDto>> blockedPeople() =>
    RustLib.instance.api.crateApiDiscoveryBlockedPeople();
