// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Subscribe to the core event stream. Call once at startup; the core pushes
/// every `discovery.updated` / `message.received` / `transfer.*` event here.
Stream<CoreEvent> coreEventStream() =>
    RustLib.instance.api.crateApiEventsCoreEventStream();
