// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// The local persona.
Future<PersonaDto> currentPersona() =>
    RustLib.instance.api.crateApiIdentityCurrentPersona();

/// Update the local persona's name and colour, bumping its version.
Future<PersonaDto> updatePersona({required String name, required int colour}) =>
    RustLib.instance.api.crateApiIdentityUpdatePersona(
      name: name,
      colour: colour,
    );

/// The colours offered on first launch.
///
/// Served from the core rather than listed again in the UI, because there are
/// already two places that must agree about a colour — what is drawn for a new
/// device, and what is offered when they change it — and a third copy in Dart
/// would be the one nobody updates. Any colour is still accepted by
/// [`update_persona`]; this is the palette, not a whitelist.
Future<List<PersonaColourDto>> personaColours() =>
    RustLib.instance.api.crateApiIdentityPersonaColours();
