// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Ping a nearby device. Emits `Pinged`.
Future<void> ping({required String deviceId}) =>
    RustLib.instance.api.crateApiMessagingPing(deviceId: deviceId);

/// Send a chat message to a device, returning the stored outgoing message. A
/// reply arrives asynchronously as a `message.received` event.
Future<ChatMessageDto> sendChat({
  required String deviceId,
  required String text,
}) => RustLib.instance.api.crateApiMessagingSendChat(
  deviceId: deviceId,
  text: text,
);

/// All messages on a thread, ordered as stored.
Future<List<ChatMessageDto>> threadMessages({
  required PlatformInt64 threadId,
}) => RustLib.instance.api.crateApiMessagingThreadMessages(threadId: threadId);
