// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Ping a nearby device. Emits `Pinged`.
Future<void> ping({required String deviceId}) =>
    RustLib.instance.api.crateApiMessagingPing(deviceId: deviceId);

/// Send a chat message to a device, returning the stored outgoing message. The
/// reply arrives later as a `message.received` event (not before this returns).
Future<ChatMessageDto> sendChat({
  required String deviceId,
  required String text,
}) => RustLib.instance.api.crateApiMessagingSendChat(
  deviceId: deviceId,
  text: text,
);

/// Send to a conversation rather than to a device — what a paired person who is
/// not currently in range is addressed by. Queues if they cannot be reached.
Future<ChatMessageDto> sendChatToThread({
  required PlatformInt64 threadId,
  required String text,
}) => RustLib.instance.api.crateApiMessagingSendChatToThread(
  threadId: threadId,
  text: text,
);

/// All messages on a thread, in chronological display order.
Future<List<ChatMessageDto>> threadMessages({
  required PlatformInt64 threadId,
}) => RustLib.instance.api.crateApiMessagingThreadMessages(threadId: threadId);

/// The existing thread with a device, if any (open a conversation without
/// sending first).
Future<PlatformInt64?> threadForDevice({required String deviceId}) =>
    RustLib.instance.api.crateApiMessagingThreadForDevice(deviceId: deviceId);

/// All conversations, for the thread list.
Future<List<ThreadSummary>> listThreads() =>
    RustLib.instance.api.crateApiMessagingListThreads();
