// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Mint a code and start showing it. Returns the text to render as a QR code
/// (and, later, to write to an NFC tag — the payload is identical).
///
/// Every call mints a fresh one, so a code that has been dismissed cannot be
/// used from a photograph.
Future<String> pairingInvite() =>
    RustLib.instance.api.crateApiPairingPairingInvite();

/// Take the code off the screen.
///
/// A ceremony already under way is unaffected: the other person is looking at
/// colours, waiting, and putting this phone down is not a decision about them.
Future<void> stopShowingInvite() =>
    RustLib.instance.api.crateApiPairingStopShowingInvite();

/// Begin pairing from a code the camera read. Returns the device id the
/// ceremony is with, which is what the events coming back are keyed on.
///
/// `Err` means the code could not be read or names a device that is not
/// nearby. Everything after that — including the code being someone else's —
/// arrives as `PairingFailed`.
Future<String> beginPairing({required String code}) =>
    RustLib.instance.api.crateApiPairingBeginPairing(code: code);

/// This person confirmed the colours match.
///
/// Never enough on its own: nothing crosses until the other side confirms too
/// (R0-F4). The UI should say "waiting" after this, not "paired".
Future<void> confirmPairing({required String deviceId}) =>
    RustLib.instance.api.crateApiPairingConfirmPairing(deviceId: deviceId);

/// Abandon a ceremony — the colours did not match, the screen closed, the other
/// person walked off. Nothing was written, so there is nothing to undo, and the
/// peer is told nothing.
Future<void> cancelPairing({required String deviceId}) =>
    RustLib.instance.api.crateApiPairingCancelPairing(deviceId: deviceId);
