// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'platform.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `from`, `from`

/// Subscribe to the host command stream. Call **before** `core_init`.
///
/// Commands issued before this lands are held rather than dropped, so a late
/// subscription costs latency and not correctness — but the core builds its
/// transports during `core_init`, so subscribing first is what keeps the very
/// first `BleSetLocalId` from waiting on the rest of startup.
Stream<HostCommand> platformCommandStream() =>
    RustLib.instance.api.crateApiPlatformPlatformCommandStream();

/// Report something the host observed.
Future<void> platformFact({required HostFact fact}) =>
    RustLib.instance.api.crateApiPlatformPlatformFact(fact: fact);

@freezed
sealed class HostCommand with _$HostCommand {
  const HostCommand._();

  /// Name the radio. Arrives on every rotation, and while Discovery is off:
  /// a hidden node still dials paired peers and must introduce itself by this
  /// id rather than its hardware address (R0-F2).
  const factory HostCommand.bleSetLocalId({required String localId}) =
      HostCommand_BleSetLocalId;

  /// Advertise this payload, replacing any current advertisement.
  const factory HostCommand.bleStartAdvertising({required Uint8List payload}) =
      HostCommand_BleStartAdvertising;

  /// Stop advertising. A real radio stop, not a flag — R0-F2 is the whole
  /// point of the Discovery switch.
  const factory HostCommand.bleStopAdvertising() =
      HostCommand_BleStopAdvertising;
  const factory HostCommand.bleStartScanning() = HostCommand_BleStartScanning;
  const factory HostCommand.bleStopScanning() = HostCommand_BleStopScanning;

  /// Open a pipe. Acceptance only: report `BlePipeOpened` or `BlePipeFailed`.
  const factory HostCommand.bleConnect({required String peer}) =
      HostCommand_BleConnect;

  /// Write to an open pipe, in order, then report `BleWriteComplete` — which
  /// is what returns the core's send-window credit.
  const factory HostCommand.bleSend({
    required String peer,
    required Uint8List bytes,
  }) = HostCommand_BleSend;
  const factory HostCommand.bleDisconnect({required String peer}) =
      HostCommand_BleDisconnect;

  /// Release every radio resource. Facts arriving after this are tolerated.
  const factory HostCommand.bleShutdown() = HostCommand_BleShutdown;
}

@freezed
sealed class HostFact with _$HostFact {
  const HostFact._();

  const factory HostFact.blePeerFound({
    required String peer,
    required Uint8List payload,
  }) = HostFact_BlePeerFound;
  const factory HostFact.blePeerLost({required String peer}) =
      HostFact_BlePeerLost;
  const factory HostFact.blePipeOpened({required String peer}) =
      HostFact_BlePipeOpened;
  const factory HostFact.blePipeFailed({
    required String peer,
    required String why,
  }) = HostFact_BlePipeFailed;
  const factory HostFact.blePipeClosed({required String peer}) =
      HostFact_BlePipeClosed;
  const factory HostFact.bleReceived({
    required String peer,
    required Uint8List bytes,
  }) = HostFact_BleReceived;

  /// The radio became usable or unusable — Bluetooth toggled, permission
  /// revoked. Reported rather than inferred, so the UI can say why.
  const factory HostFact.bleAvailability({
    required bool available,
    String? reason,
  }) = HostFact_BleAvailability;

  /// Bytes the radio has finished with.
  const factory HostFact.bleWriteComplete({
    required String peer,
    required BigInt bytes,
  }) = HostFact_BleWriteComplete;
}
