// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Offer a file (Drop) to a device. Returns the transfer id; progress and
/// completion are delivered over the event stream.
Future<String> offerDrop({
  required String deviceId,
  required String name,
  required BigInt size,
}) => RustLib.instance.api.crateApiTransfersOfferDrop(
  deviceId: deviceId,
  name: name,
  size: size,
);
