// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// A stored chat message, as the UI sees it.
class ChatMessageDto {
  final String msgId;
  final PlatformInt64 threadId;
  final String text;
  final bool outgoing;
  final PlatformInt64 createdAt;

  /// How far this one has got, for outgoing messages.
  ///
  /// Carried because the difference is real and was invisible: until the
  /// acknowledgement existed, `Sent` was terminal, so a message the other
  /// person is reading looked exactly like one they refused — and one they
  /// refused is a thing that happened, silently, on two phones.
  ///
  /// Meaningless on an incoming message, which is stored `Delivered` the
  /// moment it is written, so the screen reads this on its own lines only.
  final MessageStateDto state;

  const ChatMessageDto({
    required this.msgId,
    required this.threadId,
    required this.text,
    required this.outgoing,
    required this.createdAt,
    required this.state,
  });

  @override
  int get hashCode =>
      msgId.hashCode ^
      threadId.hashCode ^
      text.hashCode ^
      outgoing.hashCode ^
      createdAt.hashCode ^
      state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessageDto &&
          runtimeType == other.runtimeType &&
          msgId == other.msgId &&
          threadId == other.threadId &&
          text == other.text &&
          outgoing == other.outgoing &&
          createdAt == other.createdAt &&
          state == other.state;
}

@freezed
sealed class CoreEvent with _$CoreEvent {
  const CoreEvent._();

  /// The nearby-device list changed (Discovery toggled or peers moved).
  const factory CoreEvent.discoveryUpdated({
    required List<NearbyDevice> devices,
  }) = CoreEvent_DiscoveryUpdated;

  /// A device pinged us.
  const factory CoreEvent.pinged({
    required String deviceId,
    required String name,
  }) = CoreEvent_Pinged;

  /// A ping we sent was answered.
  ///
  /// Separate from the "pinged" event, which is someone nudging us. While the
  /// two were one event, a tap looked answered only if the other person
  /// happened to nudge back — so an ordinary ping always timed out, and an
  /// unrelated incoming one was mistaken for the answer.
  ///
  /// Named in prose rather than as a Rust path, because this comment is
  /// copied verbatim into the generated Dart, where such a link points at
  /// nothing.
  const factory CoreEvent.pingAcked({required String deviceId}) =
      CoreEvent_PingAcked;

  /// A Ping could not be delivered — the pipe never opened.
  ///
  /// Only ever raised for a peer we failed to *reach*. A blocked peer accepts
  /// the connection and then goes quiet during the handshake, so it produces
  /// no event at all — which is what keeps "blocked" indistinguishable from
  /// "not there" (R0-F10).
  const factory CoreEvent.pingFailed({
    required String deviceId,
    required String reason,
  }) = CoreEvent_PingFailed;

  /// A message arrived on a thread.
  const factory CoreEvent.messageReceived({
    required PlatformInt64 threadId,
    required String msgId,
    required String text,
  }) = CoreEvent_MessageReceived;

  /// Progress on an in-flight transfer.
  const factory CoreEvent.transferProgress({
    required String transferId,
    required BigInt received,
    required BigInt total,
  }) = CoreEvent_TransferProgress;

  /// A transfer finished (or failed).
  const factory CoreEvent.transferCompleted({
    required String transferId,
    required bool success,
  }) = CoreEvent_TransferCompleted;

  /// A pairing ceremony reached the point where two people compare colours.
  ///
  /// Nothing has been disclosed and nothing is written down. The only thing
  /// that may happen next is a person looking at a screen and deciding.
  ///
  /// The colours are a list rather than a fixed pair on purpose. How many
  /// there are is a security parameter — each one is four bits of what an
  /// active relay has to guess — and that number is still open. A UI written
  /// against a list survives the decision; one written against `first` and
  /// `second` does not.
  ///
  /// Order carries information: "teal then amber" is not "amber then teal",
  /// so it must be rendered as given and never sorted.
  ///
  /// Carried directly on the event rather than wrapped in a `Sas` struct,
  /// which is not tidiness — it is the only version with working equality in
  /// Dart. The generated enum variants compare list fields with
  /// `DeepCollectionEquality`, but a nested plain struct is compared with its
  /// own `==`, and the generator gives those reference equality on lists. So
  /// two identical SAS values would have compared unequal, silently, for as
  /// long as anyone cared to look.
  const factory CoreEvent.pairingSas({
    required String deviceId,
    required List<SasColourDto> colours,
    required String word,
  }) = CoreEvent_PairingSas;

  /// The other person confirmed.
  ///
  /// A cue, not a result: on its own it means nothing has crossed. Showing it
  /// as "paired" would be a lie the protocol is specifically built to avoid.
  const factory CoreEvent.pairingPeerConfirmed({required String deviceId}) =
      CoreEvent_PairingPeerConfirmed;

  /// Both people confirmed, both identities checked out, and the thread
  /// exists. This is a pairing (R0-F4).
  const factory CoreEvent.pairingCompleted({
    required String deviceId,
    required PlatformInt64 threadId,
    required String name,
    required int colour,
  }) = CoreEvent_PairingCompleted;

  /// A ceremony ended without pairing.
  ///
  /// One wording for every cause. A substituted code, a bad proof, a message
  /// out of order and a pipe that died are different things internally and
  /// the same thing to the person holding the phone — and telling them apart
  /// on screen would also tell a prober which of its guesses was closer.
  const factory CoreEvent.pairingFailed({
    required String deviceId,
    required String reason,
  }) = CoreEvent_PairingFailed;

  /// The radio became usable or unusable.
  ///
  /// A device list cannot carry this on its own: an empty list is what both
  /// "the radio is off" and "nobody is nearby" look like, and R0-F2 turns on
  /// the user being able to tell those apart. `reason` is absent when the
  /// radio is fine, and a sentence fit to show when it is not — written by
  /// the rung, because only the rung knows.
  ///
  /// `available` is the source of truth; `reason` is decoration on top of it.
  /// A report can be unavailable with nothing to say, so anything deciding
  /// from the presence of a reason gets the state backwards.
  ///
  /// Kept free of Rust names and Rust paths on purpose: this comment is
  /// copied verbatim into the generated Dart, where `None` and
  /// `CoreEvent::DiscoveryUpdated` mean nothing to the reader.
  const factory CoreEvent.radioChanged({
    required bool available,
    String? reason,
  }) = CoreEvent_RadioChanged;
}

/// What a message's row is entitled to claim.
///
/// Deliberately three states rather than a `delivered: bool`. A flag collapses
/// "we have not sent it yet" and "we sent it and heard nothing" into one
/// negative, and those are the two the person on the other end of a queued
/// backlog most needs told apart.
enum MessageStateDto {
  /// Written, and still on this device. Nothing has left.
  queued,

  /// The bytes left. Nobody has confirmed anything, and on an unpaired
  /// thread nobody ever will — there is no ratchet to seal an
  /// acknowledgement with, so this is as far as those rows go.
  sent,

  /// The far side said it has it, sealed on a chain only they hold.
  delivered,
}

/// Someone the app can show: a device in range, or a person we have paired
/// with and are not currently in range of.
///
/// Both, because R0-F2 rotates transport ids every twelve minutes and R0-F4
/// says pairing survives that. A list built only from what the radio can see
/// drops a paired person the moment they stop advertising — the app forgetting
/// someone the user deliberately introduced it to.
class NearbyDevice {
  /// Opaque transport handle, and `None` when they are not in range.
  ///
  /// The caller passes it back to `ping` / `send_chat` / `offer_drop`, so its
  /// absence *is* "cannot be reached right now" — one fact, not a presence
  /// flag alongside a handle that could disagree with it. Deliberately not a
  /// stand-in identity when they are away: an earlier attempt put a durable
  /// pseudonym in this field and made every transport-routed action on an
  /// away row unroutable, because Ping and Drop had nothing to dial.
  final String? deviceId;

  /// The conversation with this person, once there is one.
  ///
  /// What an away row is addressed by. A thread outlives every id the peer
  /// advertises under, so it is the handle that still means something when
  /// the radio can no longer see them.
  final PlatformInt64? threadId;
  final String name;
  final int colour;
  final bool paired;

  const NearbyDevice({
    this.deviceId,
    this.threadId,
    required this.name,
    required this.colour,
    required this.paired,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      threadId.hashCode ^
      name.hashCode ^
      colour.hashCode ^
      paired.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NearbyDevice &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          threadId == other.threadId &&
          name == other.name &&
          colour == other.colour &&
          paired == other.paired;
}

/// One of the colours a person may pick for themselves (R0-F1).
///
/// Carries its name because a row of coloured circles is unusable to somebody
/// who cannot tell them apart, and roughly one man in twelve cannot tell at
/// least two of these apart. The name is what the screen reader reads and what
/// distinguishes the swatches when the colour does not.
class PersonaColourDto {
  /// What to call it: "blue", "coral".
  final String name;

  /// Packed 0xRRGGBB, as [`PersonaDto::colour`].
  final int value;

  const PersonaColourDto({required this.name, required this.value});

  @override
  int get hashCode => name.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PersonaColourDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          value == other.value;
}

/// The local persona shown in Discovery and edited in the UI.
class PersonaDto {
  final String name;

  /// Packed 0xRRGGBB.
  final int colour;
  final int version;

  /// Nobody has chosen this name yet — it is the placeholder the core made up.
  ///
  /// R0-F1 says the person chooses a display name on first launch, and until
  /// now no step ever asked, so every device shipped called "Me". The visible
  /// cost landed on the pairing screen, which read "Pairing with Me" on the
  /// one screen whose whole job is saying who is at the other end.
  ///
  /// Derived rather than stored as a flag: a persona is written down only
  /// when somebody chooses one, so "nothing stored" *is* "never chosen" and
  /// the two cannot disagree.
  final bool needsName;

  const PersonaDto({
    required this.name,
    required this.colour,
    required this.version,
    required this.needsName,
  });

  @override
  int get hashCode =>
      name.hashCode ^ colour.hashCode ^ version.hashCode ^ needsName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PersonaDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          colour == other.colour &&
          version == other.version &&
          needsName == other.needsName;
}

/// One colour of a pairing SAS: what to paint, and what to call it.
///
/// Both, because a swatch cannot be compared over a phone call and cannot be
/// compared at all by a colour-blind person — and this is the step that decides
/// whether their pairing is safe.
class SasColourDto {
  final String name;

  /// Packed 0xRRGGBB.
  final int rgb;

  const SasColourDto({required this.name, required this.rgb});

  @override
  int get hashCode => name.hashCode ^ rgb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SasColourDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          rgb == other.rgb;
}

/// A conversation, for the UI's thread list.
class ThreadSummary {
  final PlatformInt64 threadId;
  final String name;
  final int colour;

  const ThreadSummary({
    required this.threadId,
    required this.name,
    required this.colour,
  });

  @override
  int get hashCode => threadId.hashCode ^ name.hashCode ^ colour.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadSummary &&
          runtimeType == other.runtimeType &&
          threadId == other.threadId &&
          name == other.name &&
          colour == other.colour;
}
