// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

/// A stored chat message, as the UI sees it.
class ChatMessageDto {
  final String msgId;
  final PlatformInt64 threadId;
  final String text;
  final bool outgoing;
  final PlatformInt64 createdAt;

  const ChatMessageDto({
    required this.msgId,
    required this.threadId,
    required this.text,
    required this.outgoing,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      msgId.hashCode ^
      threadId.hashCode ^
      text.hashCode ^
      outgoing.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessageDto &&
          runtimeType == other.runtimeType &&
          msgId == other.msgId &&
          threadId == other.threadId &&
          text == other.text &&
          outgoing == other.outgoing &&
          createdAt == other.createdAt;
}

@freezed
sealed class CoreEvent with _$CoreEvent {
  const CoreEvent._();

  /// The nearby-device list changed (Discovery toggled or peers moved).
  const factory CoreEvent.discoveryUpdated({
    required List<NearbyDevice> devices,
  }) = CoreEvent_DiscoveryUpdated;

  /// A device pinged us.
  const factory CoreEvent.pinged({
    required String deviceId,
    required String name,
  }) = CoreEvent_Pinged;

  /// A ping we sent was answered.
  ///
  /// Separate from the "pinged" event, which is someone nudging us. While the
  /// two were one event, a tap looked answered only if the other person
  /// happened to nudge back — so an ordinary ping always timed out, and an
  /// unrelated incoming one was mistaken for the answer.
  ///
  /// Named in prose rather than as a Rust path, because this comment is
  /// copied verbatim into the generated Dart, where such a link points at
  /// nothing.
  const factory CoreEvent.pingAcked({required String deviceId}) =
      CoreEvent_PingAcked;

  /// A Ping could not be delivered — the pipe never opened.
  ///
  /// Only ever raised for a peer we failed to *reach*. A blocked peer accepts
  /// the connection and then goes quiet during the handshake, so it produces
  /// no event at all — which is what keeps "blocked" indistinguishable from
  /// "not there" (R0-F10).
  const factory CoreEvent.pingFailed({
    required String deviceId,
    required String reason,
  }) = CoreEvent_PingFailed;

  /// A message arrived on a thread.
  const factory CoreEvent.messageReceived({
    required PlatformInt64 threadId,
    required String msgId,
    required String text,
  }) = CoreEvent_MessageReceived;

  /// Progress on an in-flight transfer.
  const factory CoreEvent.transferProgress({
    required String transferId,
    required BigInt received,
    required BigInt total,
  }) = CoreEvent_TransferProgress;

  /// A transfer finished (or failed).
  const factory CoreEvent.transferCompleted({
    required String transferId,
    required bool success,
  }) = CoreEvent_TransferCompleted;

  /// The radio became usable or unusable.
  ///
  /// A device list cannot carry this on its own: an empty list is what both
  /// "the radio is off" and "nobody is nearby" look like, and R0-F2 turns on
  /// the user being able to tell those apart. `reason` is absent when the
  /// radio is fine, and a sentence fit to show when it is not — written by
  /// the rung, because only the rung knows.
  ///
  /// `available` is the source of truth; `reason` is decoration on top of it.
  /// A report can be unavailable with nothing to say, so anything deciding
  /// from the presence of a reason gets the state backwards.
  ///
  /// Kept free of Rust names and Rust paths on purpose: this comment is
  /// copied verbatim into the generated Dart, where `None` and
  /// `CoreEvent::DiscoveryUpdated` mean nothing to the reader.
  const factory CoreEvent.radioChanged({
    required bool available,
    String? reason,
  }) = CoreEvent_RadioChanged;
}

/// A device visible in Discovery.
class NearbyDevice {
  /// Opaque stable handle for this device (the caller passes it back to
  /// `ping` / `send_chat` / `offer_drop`).
  final String deviceId;
  final String name;
  final int colour;
  final bool paired;

  const NearbyDevice({
    required this.deviceId,
    required this.name,
    required this.colour,
    required this.paired,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^ name.hashCode ^ colour.hashCode ^ paired.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NearbyDevice &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          name == other.name &&
          colour == other.colour &&
          paired == other.paired;
}

/// The local persona shown in Discovery and edited in the UI.
class PersonaDto {
  final String name;

  /// Packed 0xRRGGBB.
  final int colour;
  final int version;

  const PersonaDto({
    required this.name,
    required this.colour,
    required this.version,
  });

  @override
  int get hashCode => name.hashCode ^ colour.hashCode ^ version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PersonaDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          colour == other.colour &&
          version == other.version;
}

/// A conversation, for the UI's thread list.
class ThreadSummary {
  final PlatformInt64 threadId;
  final String name;
  final int colour;

  const ThreadSummary({
    required this.threadId,
    required this.name,
    required this.colour,
  });

  @override
  int get hashCode => threadId.hashCode ^ name.hashCode ^ colour.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadSummary &&
          runtimeType == other.runtimeType &&
          threadId == other.threadId &&
          name == other.name &&
          colour == other.colour;
}
