// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

/// A stored chat message, as the UI sees it.
class ChatMessageDto {
  final String msgId;
  final PlatformInt64 threadId;
  final String text;
  final bool outgoing;
  final PlatformInt64 createdAt;

  const ChatMessageDto({
    required this.msgId,
    required this.threadId,
    required this.text,
    required this.outgoing,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      msgId.hashCode ^
      threadId.hashCode ^
      text.hashCode ^
      outgoing.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessageDto &&
          runtimeType == other.runtimeType &&
          msgId == other.msgId &&
          threadId == other.threadId &&
          text == other.text &&
          outgoing == other.outgoing &&
          createdAt == other.createdAt;
}

@freezed
sealed class CoreEvent with _$CoreEvent {
  const CoreEvent._();

  /// The nearby-device list changed (Discovery toggled or peers moved).
  const factory CoreEvent.discoveryUpdated({
    required List<NearbyDevice> devices,
  }) = CoreEvent_DiscoveryUpdated;

  /// A device pinged us (or our ping was acknowledged).
  const factory CoreEvent.pinged({
    required String deviceId,
    required String name,
  }) = CoreEvent_Pinged;

  /// A message arrived on a thread.
  const factory CoreEvent.messageReceived({
    required PlatformInt64 threadId,
    required String msgId,
    required String text,
  }) = CoreEvent_MessageReceived;

  /// Progress on an in-flight transfer.
  const factory CoreEvent.transferProgress({
    required String transferId,
    required BigInt received,
    required BigInt total,
  }) = CoreEvent_TransferProgress;

  /// A transfer finished (or failed).
  const factory CoreEvent.transferCompleted({
    required String transferId,
    required bool success,
  }) = CoreEvent_TransferCompleted;
}

/// A device visible in Discovery.
class NearbyDevice {
  /// Opaque stable handle for this device (the caller passes it back to
  /// `ping` / `send_chat` / `offer_drop`).
  final String deviceId;
  final String name;
  final int colour;
  final bool paired;

  const NearbyDevice({
    required this.deviceId,
    required this.name,
    required this.colour,
    required this.paired,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^ name.hashCode ^ colour.hashCode ^ paired.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NearbyDevice &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          name == other.name &&
          colour == other.colour &&
          paired == other.paired;
}

/// The local persona shown in Discovery and edited in the UI.
class PersonaDto {
  final String name;

  /// Packed 0xRRGGBB.
  final int colour;
  final int version;

  const PersonaDto({
    required this.name,
    required this.colour,
    required this.version,
  });

  @override
  int get hashCode => name.hashCode ^ colour.hashCode ^ version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PersonaDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          colour == other.colour &&
          version == other.version;
}

/// A conversation, for the UI's thread list.
class ThreadSummary {
  final PlatformInt64 threadId;
  final String name;
  final int colour;

  const ThreadSummary({
    required this.threadId,
    required this.name,
    required this.colour,
  });

  @override
  int get hashCode => threadId.hashCode ^ name.hashCode ^ colour.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadSummary &&
          runtimeType == other.runtimeType &&
          threadId == other.threadId &&
          name == other.name &&
          colour == other.colour;
}
